add Darwin support

diff --git a/aliases/aliases b/aliases/aliases
--- a/aliases/aliases
+++ b/aliases/aliases
@@ -1,25 +1,39 @@
 #!/bin/bash
 
+# funcs.
+die() { echo "$1" >&2; exit "${2:-1}"; }
+
+# get os.
+os=$(uname) \
+  || die "failed to get operating system"
+
 # zsh.
 alias d='dirs -v' # enables jump-back alias for previously visited directories.
 for index ({0..9}) alias "$index"="cd +${index}"; unset index
 
 # aws.
 aws() {
-    case $* in
-        # who am I authed as?
-        auth) command aws sts get-caller-identity ;;
-        # what is the arn I am authed as?
-        who) command aws sts get-caller-identity --query "Arn" --output text ;;
-        # quick auth to ECR.
-        ecr) command aws ecr get-login --no-include-email --region "$AWS_DEFAULT_REGION" ;;
-        # run "default" command.
-        *) command aws "$@" ;;
-    esac
+  case $* in
+    # who am I authed as?
+    auth) command aws sts get-caller-identity ;;
+    # what is the arn I am authed as?
+    who) command aws sts get-caller-identity --query "Arn" --output text ;;
+    # quick auth to ECR.
+    ecr) command aws ecr get-login --no-include-email --region "$AWS_DEFAULT_REGION" ;;
+    # run "default" command.
+    *) command aws "$@" ;;
+  esac
 }
 
 # general.
-alias ls='ls --color=auto'
+case "$os" in
+  Darwin)
+    alias ls='ls -G'
+  ;;
+  Linux)
+    alias ls='ls --color=auto'
+  ;;
+esac
 alias grep='grep --color=auto'
 alias dotfiles='code $DOTFILES'
-alias zsrc='source $HOME/.zshrc'
+alias zsrc='source $DOTFILES/aliases/aliases $HOME/.zshenv $HOME/.zshrc'
